-- Run this in your Supabase project: SQL Editor → New Query → paste → Run

create table public.features (
  id          bigint generated by default as identity primary key,
  name        text not null,
  date        text not null,
  description text not null default '',
  cat         text not null default 'Core Gameplay',
  status      text not null default 'Planned',
  impact      text not null default 'Medium',
  owner       text not null default 'Product'
);

-- Allow anyone with the link to read + write (internal tool)
alter table public.features enable row level security;

create policy "public read"   on public.features for select using (true);
create policy "public insert" on public.features for insert with check (true);
create policy "public update" on public.features for update using (true);
create policy "public delete" on public.features for delete using (true);

-- Seed data
insert into public.features (name, date, description, cat, status, impact, owner) values
  ('Battleship Mini Game Event',    '2026-03-18', 'Limited-time naval battle event with exclusive rewards and leaderboards.',         'LiveOps Event',    'QA',              'High',   'Product'),
  ('New Character Skins Pack',      '2026-03-20', 'Six vibrant character skin variants available through the in-game shop.',          'Monetization',     'Ready to Launch', 'Low',    'Design'),
  ('Boink Fleet Feature',           '2026-03-22', 'Fleet management meta-layer letting players build and upgrade ship squads.',        'Core Gameplay',    'In Development',  'High',   'Engineering'),
  ('New Sticker Album',             '2026-03-25', 'Collectible sticker album with 60 stickers to unlock through gameplay.',           'Meta Progression', 'In Development',  'Medium', 'Design'),
  ('Daily Challenge System',        '2026-03-28', 'Rotating daily challenges with scaling rewards designed to boost DAU.',            'Core Gameplay',    'QA',              'Medium', 'Product'),
  ('Cosmic Road Progression Update','2026-04-02', 'Revamped progression track with cosmic theme, new milestones and visual rewards.', 'Meta Progression', 'Planned',         'High',   'Product'),
  ('DC Economy Update',             '2026-04-07', 'Rebalanced Dynamic Currency economy with new earning mechanics and premium rates.','Monetization',     'In Development',  'High',   'Product'),
  ('PvP Battle Balancing',          '2026-04-10', 'Comprehensive rebalance of PvP matchmaking algorithms and power scaling curves.',  'Core Gameplay',    'QA',              'Medium', 'Engineering'),
  ('Seasonal LiveOps Event',        '2026-04-15', 'Spring-themed event with exclusive cosmetics and time-limited challenges.',         'LiveOps Event',    'Planned',         'High',   'Product'),
  ('Push Notification Revamp',      '2026-04-20', 'Smart personalized push system with frequency caps and A/B testing segmentation.', 'Infrastructure',   'In Development',  'Medium', 'Engineering'),
  ('VIP Rewards Tier System',       '2026-04-28', 'Tiered VIP program offering exclusive perks and recognition for top spenders.',    'Monetization',     'Planned',         'High',   'Product'),
  ('Club Leaderboards V2',          '2026-05-01', 'Revamped club competition with weekly seasons, trophies and club progression.',    'Meta Progression', 'Planned',         'High',   'Engineering');
